services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: coworkspace_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      # niente init SQL: il bootstrap Node crea lo schema
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d coworkspace_db"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build: ./backend
    depends_on:
      - db
    restart: on-failure
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
      DB_NAME: coworkspace_db
      DB_BOOTSTRAP: "true"
      JWT_SECRET: dev_super_secret_change_me
      PORT: 3000
      CORS_ORIGINS: http://localhost:5173,http://127.0.0.1:5173
    ports:
      - "3000:3000"

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db_data:
