version: '3.8'
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: coworkspace_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./SQL/setup.sql:/docker-entrypoint-initdb.d/setup.sql:ro

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
      DB_NAME: coworkspace_db
      JWT_SECRET: dev_super_secret_change_me
      PORT: 3000
      CORS_ORIGINS: http://localhost:5173,http://127.0.0.1:5173
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend_2
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db_data:
